// <auto-generated />
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DbContextCarCode))]
    partial class DbContextCarCodeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.CarNumberCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("CarNumberCodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionCode = "AA",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            RegionCode = "KA",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            RegionCode = "AB",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 4,
                            RegionCode = "KB",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 5,
                            RegionCode = "AC",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 6,
                            RegionCode = "KC",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 7,
                            RegionCode = "AE",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 8,
                            RegionCode = "KE",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 9,
                            RegionCode = "AH",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 10,
                            RegionCode = "KH",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 11,
                            RegionCode = "AI",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 12,
                            RegionCode = "KI",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 13,
                            RegionCode = "AM",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 14,
                            RegionCode = "KM",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 15,
                            RegionCode = "AO",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 16,
                            RegionCode = "KO",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 17,
                            RegionCode = "AP",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 18,
                            RegionCode = "KP",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 19,
                            RegionCode = "AT",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 20,
                            RegionCode = "KT",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 21,
                            RegionCode = "AX",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 22,
                            RegionCode = "KX",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 23,
                            RegionCode = "BA",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 24,
                            RegionCode = "HA",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 25,
                            RegionCode = "BB",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 26,
                            RegionCode = "HB",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 27,
                            RegionCode = "BC",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 28,
                            RegionCode = "HC",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 29,
                            RegionCode = "BE",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 30,
                            RegionCode = "HE",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 31,
                            RegionCode = "BH",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 32,
                            RegionCode = "HH",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 33,
                            RegionCode = "BI",
                            RegionId = 17
                        },
                        new
                        {
                            Id = 34,
                            RegionCode = "HI",
                            RegionId = 17
                        },
                        new
                        {
                            Id = 35,
                            RegionCode = "BK",
                            RegionId = 18
                        },
                        new
                        {
                            Id = 36,
                            RegionCode = "HK",
                            RegionId = 18
                        },
                        new
                        {
                            Id = 37,
                            RegionCode = "BM",
                            RegionId = 19
                        },
                        new
                        {
                            Id = 38,
                            RegionCode = "HM",
                            RegionId = 19
                        },
                        new
                        {
                            Id = 39,
                            RegionCode = "BO",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 40,
                            RegionCode = "HO",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 41,
                            RegionCode = "BT",
                            RegionId = 21
                        },
                        new
                        {
                            Id = 42,
                            RegionCode = "HT",
                            RegionId = 21
                        },
                        new
                        {
                            Id = 43,
                            RegionCode = "BX",
                            RegionId = 22
                        },
                        new
                        {
                            Id = 44,
                            RegionCode = "HX",
                            RegionId = 22
                        },
                        new
                        {
                            Id = 45,
                            RegionCode = "CA",
                            RegionId = 23
                        },
                        new
                        {
                            Id = 46,
                            RegionCode = "IA",
                            RegionId = 23
                        },
                        new
                        {
                            Id = 47,
                            RegionCode = "CB",
                            RegionId = 24
                        },
                        new
                        {
                            Id = 48,
                            RegionCode = "IB",
                            RegionId = 24
                        },
                        new
                        {
                            Id = 49,
                            RegionCode = "CE",
                            RegionId = 25
                        },
                        new
                        {
                            Id = 50,
                            RegionCode = "IE",
                            RegionId = 25
                        },
                        new
                        {
                            Id = 51,
                            RegionCode = "II",
                            RegionId = 26
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RegionName = "Київ"
                        },
                        new
                        {
                            Id = 2,
                            RegionName = "Вінницька"
                        },
                        new
                        {
                            Id = 3,
                            RegionName = "Волинська"
                        },
                        new
                        {
                            Id = 4,
                            RegionName = "Дніпропетровська"
                        },
                        new
                        {
                            Id = 5,
                            RegionName = "Донецька"
                        },
                        new
                        {
                            Id = 6,
                            RegionName = "Київська"
                        },
                        new
                        {
                            Id = 7,
                            RegionName = "Житомирська"
                        },
                        new
                        {
                            Id = 8,
                            RegionName = "Закарпатська"
                        },
                        new
                        {
                            Id = 9,
                            RegionName = "Запорізька"
                        },
                        new
                        {
                            Id = 10,
                            RegionName = "Івано-Франківська"
                        },
                        new
                        {
                            Id = 11,
                            RegionName = "Харківська"
                        },
                        new
                        {
                            Id = 12,
                            RegionName = "Кіровоградська"
                        },
                        new
                        {
                            Id = 13,
                            RegionName = "Луганська"
                        },
                        new
                        {
                            Id = 14,
                            RegionName = "Львівська"
                        },
                        new
                        {
                            Id = 15,
                            RegionName = "Миколаївська"
                        },
                        new
                        {
                            Id = 16,
                            RegionName = "Одеська"
                        },
                        new
                        {
                            Id = 17,
                            RegionName = "Полтавська"
                        },
                        new
                        {
                            Id = 18,
                            RegionName = "Рівненська"
                        },
                        new
                        {
                            Id = 19,
                            RegionName = "Сумська"
                        },
                        new
                        {
                            Id = 20,
                            RegionName = "Тернопільська"
                        },
                        new
                        {
                            Id = 21,
                            RegionName = "Херсонська"
                        },
                        new
                        {
                            Id = 22,
                            RegionName = "Хмельницька"
                        },
                        new
                        {
                            Id = 23,
                            RegionName = "Черкаська"
                        },
                        new
                        {
                            Id = 24,
                            RegionName = "Чернігівська"
                        },
                        new
                        {
                            Id = 25,
                            RegionName = "Чернівецька"
                        },
                        new
                        {
                            Id = 26,
                            RegionName = "Загальнодержавна серія"
                        });
                });

            modelBuilder.Entity("DataAccess.Entities.CarNumberCode", b =>
                {
                    b.HasOne("DataAccess.Entities.Region", "Region")
                        .WithMany("RegionCodes")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DataAccess.Entities.Region", b =>
                {
                    b.Navigation("RegionCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
